language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.1.1
gemfile:
  - Gemfile
  - gemfiles/ar3.1.gemfile
  - gemfiles/ar3.2.gemfile
  - gemfiles/ar4.0.gemfile
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
