language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4

gemfile:
  - gemfiles/ar3.1.gemfile
  - gemfiles/ar3.2.gemfile
  - gemfiles/ar4.0.gemfile
  - gemfiles/ar4.1.gemfile
  - gemfiles/ar4.2.gemfile
  - gemfiles/ar5.0.gemfile
  - gemfiles/ar5.1.gemfile
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
  - gemfiles/mongoid4.gemfile
  - gemfiles/mongoid5.gemfile
  - gemfiles/mongoid6.gemfile
  - gemfiles/noorm.gemfile

sudo: false

services:
  - mongodb

before_script:
  - cp integration/active_record/database.yml.example integration/active_record/database.yml;
  - mysql -e 'create database blueprints_boy_test;'

matrix:
  exclude:
  - rvm: 2.1
    gemfile: gemfiles/ar5.0.gemfile
  - rvm: 2.1
    gemfile: gemfiles/ar5.1.gemfile
  - rvm: 2.2
    gemfile: gemfiles/ar5.1.gemfile
  - rvm: 2.2
    gemfile: gemfiles/ar5.0.gemfile
  - rvm: 2.4
    gemfile: gemfiles/ar3.1.gemfile
  - rvm: 2.4
    gemfile: gemfiles/ar3.2.gemfile
  - rvm: 2.4
    gemfile: gemfiles/ar4.0.gemfile
  - rvm: 2.4
    gemfile: gemfiles/ar4.1.gemfile
